config/routes.rb
Rails.application.routes.draw do
  get 'spts/index'
  get 'spts/about', :to => 'spts#about'
  get 'spts/developers_portal', :to => 'spts#developers_portal'
  post 'spts/student_login', :to => 'spts#student_login'
  post 'spts/faculty_login', :to => 'spts#faculty_login'
  delete 'spts/logout', :to => 'spts#logout'
  root 'spts#index'

  get 'student/dashboard', :to => 'students#dashboard'
  get 'student/charts', :to => 'students#charts'
  get 'student/grades', :to => 'students#grades'
  get 'student/unitsEarned', :to => 'students#unitsEarned'
  get 'student/unitsToGo', :to => 'students#unitsToGo'
  
  resources :admins
  get 'admin/dashboard', :to => 'admins#dashboard'
  post 'admin/dashboard', :to => 'admins#dashboard'
  get 'admin/add_new_subject', :to => 'admins#add_new_subject'
  post 'admin/add_new_subject', :to => 'admins#new_subject'
  get 'admin/new_subject', :to => 'admins#new_subject'
  post 'admin/new_subject', :to => 'admins#new_subject'
  get 'admin/new_subject', :to => 'admins#new_subject'
  get 'admin/add_study_path', :to => 'admins#add_study_path'
  get 'admin/view_study_path', :to => 'admins#view_study_path'
  get 'admin/remove_study_path', :to => 'admins#remove_study_path'
  get 'admin/:id/delete_certain_study_path', :to => 'admins#delete_certain_study_path'
  
  resources :study_paths
  get 'study_path/:id/remove_subject', :to => 'study_paths#remove_subject', as: 'remove_subject'
  get 'study_path/:id/add_subject', :to => 'study_paths#add_subject', as: 'add_subject'
  get 'study_path/:id/update_subjects', :to => 'study_paths#update_subjects', as: 'update_subjects'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/admins/add_new_subject.html.erb
<body class="fixed-nav bg-dark" id="page-top">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <a class="navbar-brand" href="/dashboard">Study Path Tracking System</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
       </button>
    </nav>
    <div class="container-fluid">
      <div class ="content_wrapper bg-light">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="/admin/dashboard">Admin</a>
          </li>
          <li class="breadcrumb-item active">Update Subjects</li>
        </ol>
        <div class="text-center center-middle-text">
          <div class="text-center center-middle-text">
          <div class="row container-fluid">
              <div class="col-3"></div>
                  <div class="card col-6">
                      <div class="card-body">
                        <h3 class="text-primary">Adding New Subject</h3>
                        <h6>Please specify the necessary things below.</h6>
                         <% if flash[:new_subject] %>
                            <% if flash[:new_subject].include? "Error"%>
                              <p class='text-center open-sans-font'><h3 class = 'text-danger'><%= flash[:new_subject] %></h3>
                            <% else %>
                               <p class='text-center open-sans-font'><h3 class = 'text-success'><%= flash[:new_subject] %></h3>
                            <% end %>
                         <% end %>
                        <br>
                         <%= form_for :subject, url: admin_new_subject_path, local: true do |f| %>
                          <%= f.text_field :subject_code, class: 'form-control form-subject', autocomplete: 'off', placeholder: 'Subject Code: e.g. CMSC 11' %> 
                          <br>
                          <%= f.select :division, ['HUM', 'SOCSCI', 'NSMD', 'MGT'], {include_blank: 'Division'}, {class: 'form-control form-subject'} %>
                          <br>
                          <%= f.text_field :name, class: 'form-control form-subject', autocomplete: 'off', placeholder: 'Subject Title : e.g Introduction to Computer Science' %> 
                          <br>
                          <%= f.text_field :pre_req, class: 'form-control form-subject', autocomplete: 'off', placeholder: 'Prerequisite(s):  (separated by commas if more than one)' %> 
                          <br>
                          <%= f.text_field :units, class: 'form-control form-subject', autocomplete: 'off', placeholder: 'Units: e.g. 1, 2 ,3 ' %> 
                          <br>
                          <%= f.text_field :description, class: 'form-control form-subject', autocomplete: 'off', placeholder:  'Subject Description' %>
                          <br>
                          <%= f.select :isGE, ['false', 'true'], {include_blank: 'is GE?'},{class: 'form-control form-subject'} %>
                          <br>
                          <%= f.select :rgep, ['PE 1', 'PE 2', 'ELECTIVE', 'GE (MST)', 'GE (AH)', 'GE (SSP)', 'NSTP'], {include_blank: 'RGEP Cluster'},{class: 'form-control form-subject'} %>
                          <br>
                          <%= f.submit 'Add New Subject',class: 'form-control btn btn-primary'%>
                        <% end %>
                      </div>
                  </div>
              </div>
           </div>
      </div>
    </div>
</body>

app/views/admins/add_study_path.html.erb
<body class="fixed-nav bg-dark" id="page-top">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <a class="navbar-brand" href="/dashboard">Study Path Tracking System</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
       </button>
    </nav>
    <div class="container-fluid">
      <div class ="content_wrapper bg-light">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="/admin/dashboard">Admin</a>
          </li>
          <li class="breadcrumb-item active">Update Subjects</li>
        </ol>
        <div class="text-center center-middle-text">
          <div class="text-center center-middle-text">
          <div class="row container-fluid">
              <div class="col-3"></div>
                  <div class="card col-6">
                      <div class="card-body">
                        <h3 class="text-primary">Creating new study path</h3>
                        <h6>Please specify the necessary things below.</h6>
                        <br>
                         <%= form_for :study_path, url: study_paths_path, local: true do |f| %>
                          <%= f.text_field :program_revision_code, class: 'form-control form-study-path', autocomplete: 'off', placeholder: 'Program Revision Code' %> 
                          <%= f.select :degree_id, ['B.S. IN COMPUTER SCIENCE','B.S. IN ACCOUNTANCY','B.S IN MANAGEMENT','B.S. (BIOLOGY)','B.A. (SOCIAL SCIENCE) ECONOMICS','B.A. (SOCIAL SCIENCE) POLITICAL SCIENCE','B.A. (PSYCHOLOGY)',
                          'B.A. (COMMUNICATION ARTS)'], {include_blank: 'Name'}, {class: 'form-control form-study-path'} %>
                          <%= f.text_field :title, class: 'form-control form-study-path', autocomplete: 'off', placeholder: 'Title' %>
                          <br>
                          <%= f.submit 'Add New Study Path',class: 'form-control btn btn-primary'%>
                        <% end %>
                      </div>
                  </div>
              </div>
           </div>
      </div>
    </div>
</body>

app/views/admins/dashboard.html.erb
<body class="fixed-nav bg-dark" id="page-top">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <a class="navbar-brand" href="/dashboard">Study Path Tracking System</a>
    </nav>
    <div class="container-fluid">
      <div class ="content_wrapper bg-light">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="/">Admin</a>  
          </li>
          <li class="breadcrumb-item active">Dashboard</li>
        </ol>
      </br>
        <h1 style="color:#add8e6; font-size:350%" > &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;ADMIN</h1>
        
        <div class="text-center center-middle-text">
          <div class = "row ">
               <div class="col-6">
                  <img src="/images/admin.png" height="300" alt="Admin Icon"/>
               </div>
               <br>
               <div class="col-4 bg-secondary">
                  <br><br>
                  <div >
                    <%= link_to "Add New Study Path", admin_add_study_path_path, class: 'btn btn-primary btn-md open-sans-font', role: 'button' %>
                  </div>
                  <br>
                  <div class = "row">
                    <div class = "col-6">
                      <div >
                        <%= link_to "View Study Path", admin_view_study_path_path, class: 'btn btn-primary btn-md open-sans-font', role: 'button' %>
                      </div>
                    </div>
                    <div class = "col-6">
                        <div >
                          <%= link_to "Remove Study Path", admin_remove_study_path_path, class: 'btn btn-primary btn-md open-sans-font', role: 'button' %>
                        </div>
                    </div>
                    <br>
                  </div>
                  <br>
                   <div >
                     <%= link_to "Add New Subject", admin_add_new_subject_path, class: 'btn btn-primary btn-md open-sans-font', role: 'button' %>
                   </div>
                  <br>
                  <div >
                    <%= link_to "Logout", '/', class: 'btn btn-primary btn-md open-sans-font', role: 'button' %>
                  </div> 
               </div>
          </div>
      </div>
    </div>
</body>

app/views/admins/show.html.erb
<body class="fixed-nav sticky-footer bg-dark" id="page-top">
   <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <a class="navbar-brand" href="/dashboard">Study Path Tracking System</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
       </button>
    </nav>
  <div class="container-fluid">
      <div class ="content_wrapper bg-light">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="/admin/dashboard">Admin</a>
        </li>
        <li class="breadcrumb-item active">Study Path</li>
      </ol>
            <div class="card mb-3">
              <div class="card-header">
                <div class="text-left">
                  <strong>Program Code : </strong><span><%= @studypath.degree_id %></span>
                </div>
                <div class="text-left">
                  <strong>Program Revision Code : </strong><span><%= @studypath.program_revision_code %></span>
                </div>
                <div class="text-left">
                  <strong>Name : </strong><span><%= @program['name'] %></span>
                </div>
                <div class="text-left">
                  <strong>Title : </strong><span><%= @studypath.title %></span>
                </div>
               </div>
              <div class="card-body">
                <div class="table-responsive">
                  <table class="table table-bordered" width="100%" cellspacing="0">
                    <thead class="thead-light">
                      <tr>
                        <th>Subject</th>
                        <th>Name</th>
                        <th>Units</th>
                        <th>Prerequisites</th>
                        <th>Grade</th>
                      </tr>
                    </thead>
                    <% if !@subjects.nil? %>
                      <% @subjects.each do |content| %>
                        <tbody>
                          <tr class="table-primary">
                            <td colspan="5">
                              <h6 class="d-inline"><%= content[:year] + " Year - " + content[:semester] + " Semester" %></h6>
                              <div class="d-inline float-right">
                                <%= link_to update_subjects_path(@studypath, "year" => content[:year], "semester" => content[:semester]), class: 'btn btn-warning btn-sm', role: 'button' do %>
                                  <i class="fa fa-fw fa-plus-square"></i> Update Subjects
                                <% end %>
                              </div>                        
                            </td>
                          <tr>  
                        </tbody>
                        <tbody>
                          <% content[:subjects].each do |subj| %>
                            <tr>
                               <%if subj.instance_of? RgepCluster%>
                                  <td><%= subj.name %></td>
                                  <td></td>
                                  <td></td>
                                  <td></td>
                                  <td></td>
                               <% else %>
                                  <td><%= subj.subject_id %></td>
                                  <td><%= subj.name %></td>
                                  <td><%= subj.units %></td>
                                  <td><%= subj.pre_req %></td>
                                  <td></td>
                               <% end %>
                            </tr>
                          <% end %>
                        </tbody>
                      <% end %>
                    <% end %>
                  </table>
                </div>
              </div>
            </div>
          </div>
        </div>
       </div>
     </div>
</body>

app/views/admins/view_study_path.html.erb
<body class="fixed-nav bg-dark" id="page-top">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
      <a class="navbar-brand" href="/dashboard">Study Path Tracking System</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
       </button>
    </nav>
    <div class="container-fluid">
      <div class ="content_wrapper bg-light">
        <ol class="breadcrumb">
          <li class="breadcrumb-item">
            <a href="/admin/dashboard">Admin</a>
          </li>
          <li class="breadcrumb-item active">Update Subjects</li>
        </ol>
        <div class="card-body">
           <h3 class="text-primary">Existing Study Paths</h3>
           <br>
           <div class="table-responsive">
                <table class="table table-bordered" width="100%" cellspacing="0">
                    <% if @study_path_courses.length > 0 %>
                        <thead class="thead-light">
                          <tr>
                            <th>Study Paths Available</th>
                            <th></th>
                          </tr>
                        </thead>
                       <% @study_path_courses.each do |content| %>
                          <tbody>
                            <tr>
                              <td><%= content[:degree].name %></td>
                              <td>
                                <% if @is_remove %>
                                    <%= link_to "/admin/#{content[:study_path_id]}/delete_certain_study_path" do %>
                                      <i class="fa fa-fw fa-trash"></i> Remove Study Path
                                     <%end%>
                                <% else %>
                                     <%= link_to "/admins/#{content[:study_path_id]}" do %>
                                      <i class="fa fa-fw fa-eye"></i> View Study Path
                                     <%end%>
                                <% end %>
                              </td>
                            </tr>
                          </tbody>
                      <% end %>
                     <% else %>
                        <thead class="thead-light">
                          <tr>
                            <th>NO Study Path Available</th>
                            <th></th>
                          </tr>
                        </thead>
                    <% end %>
                </table>
           </div>
        </div>
     </div>
  </div> 
</body>