config/routes.rb
Rails.application.routes.draw do
  get 'spts/index'
  get 'spts/about', :to => 'spts#about'
  get 'spts/developers_portal', :to => 'spts#developers_portal'
  post 'spts/student_login', :to => 'spts#student_login'
  post 'spts/faculty_login', :to => 'spts#faculty_login'
  delete 'spts/logout', :to => 'spts#logout'
  root 'spts#index'

  get 'student/dashboard', :to => 'students#dashboard'
  get 'student/charts', :to => 'students#charts'
  get 'student/grades', :to => 'students#grades'
  get 'student/unitsEarned', :to => 'students#unitsEarned'
  get 'student/unitsToGo', :to => 'students#unitsToGo'
  
  resources :admins
  get 'admin/dashboard', :to => 'admins#dashboard'
  post 'admin/dashboard', :to => 'admins#dashboard'
  get 'admin/add_new_subject', :to => 'admins#add_new_subject'
  post 'admin/add_new_subject', :to => 'admins#new_subject'
  get 'admin/new_subject', :to => 'admins#new_subject'
  post 'admin/new_subject', :to => 'admins#new_subject'
  get 'admin/new_subject', :to => 'admins#new_subject'
  get 'admin/add_study_path', :to => 'admins#add_study_path'
  get 'admin/view_study_path', :to => 'admins#view_study_path'
  get 'admin/remove_study_path', :to => 'admins#remove_study_path'
  get 'admin/:id/delete_certain_study_path', :to => 'admins#delete_certain_study_path'
  
  resources :study_paths
  get 'study_path/:id/remove_subject', :to => 'study_paths#remove_subject', as: 'remove_subject'
  get 'study_path/:id/add_subject', :to => 'study_paths#add_subject', as: 'add_subject'
  get 'study_path/:id/update_subjects', :to => 'study_paths#update_subjects', as: 'update_subjects'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/spts_controller.rb
require 'faculty'
require 'student'

class SptsController < ApplicationController
  def index
    if !session[:user].nil?
      if session[:user]['type'].eql? 'student'
        redirect_to '/student/dashboard'
      else
        # redirect_to '/faculty/dashboard'
      end
    end

    @title = 'SPTS'
  end

  def about
    @title = 'SPTS - About'
  end

  def developers_portal
    @title = 'SPTS - Developers Portal'
  end

  def student_login
    @student = Student.new params[:spts][:user], params[:spts][:password]

    if @student.login
      session[:user] = {'id' => params[:spts][:user], 'password' => params[:spts][:password], 'type' => 'student'}
      redirect_to '/student/dashboard'
    else
      flash[:login_error] = "Your credentials do not match our records!"
      redirect_to '/'
    end
  end

  def faculty_login
    @admin = Admin.find_by id: 1
    if ((params[:spts][:user] == @admin.user_name) and params[:spts][:password] == @admin.password)
      session[:user] = {'id' => params[:spts][:user], 'password' => params[:spts][:password], 'type' => 'admin'}
      redirect_to '/admin/dashboard'
    else
       flash[:login_error] = "Your credentials do not match our records!"
        redirect_to '/' 
    end
  end

  def logout
    session.delete :user
    redirect_to '/'
  end
end

app/helpers/spts_helper.rb
module SptsHelper
end

app/views/spts/about.html.erb
<body>
	<div class='container-fluid bg-index full-div'>
		<div class='col-sm-9'>
			<header class='header fixed-top'>
				<div class='container-fluid text-center'>
					<%= image_tag('logo/logo-up.png', :alt => 'UP', :class => 'logo-up') %>
					<h2 class='sub-banner saira-extra-condensed-extra-bold-font'><span class='dark-green'>University of the Philippines<br></span></h2>
				</div>
			</header>
			<div class='col-sm-10 align-self-center'>
				<br>
				<h2 class='banner saira-extra-condensed-extra-bold-font'><br>STUDY PATH TRACKING SYSTEM</h2>
				<h4 class='sub-banner saira-extra-condensed-extra-bold-font'><span class='dark-green'>Your future is yours to follow</span></h4>
				<h4 class='saira-extra-condensed-semi-bold-font'>
					<font color='white'>
						Study Path Tracking System (SPTS) is an online study plan tracking tool available for every student and professor to use. Professors can log in to this app for them to be able to add or remove syllabus.
					</font>
				</h4>
			</div>
			<footer class='footer fixed-bottom'>
				<div class='container-fluid text-center'>
					<span class='text-muted open-sans-font'>Copyright © Study Path Tracking System 2018</span>
				</div>
			</footer>
		</div>
		<div class='col-sm-4'>
		</div>
	</div>
</body>

app/views/spts/developers_portal.html.erb
<body>
	<div class='container-fluid bg-index full-div'>
		<header class='header fixed-top'>
			<div class='container-fluid text-center'>
				<%= image_tag('logo/logo-up.png', :alt => 'UP', :class => 'logo-up') %>
				<h2 class='sub-banner saira-extra-condensed-extra-bold-font'><span class='dark-green'>University of the Philippines<br></span></h2>
			</div>
		</header>
		<br>
		<div>
			<br><br><br><br><h4 class='sub-banner saira-extra-condensed-extra-bold-font text-center'><font color='pink'>PENC Development Team</font></h4>
			<table cellpadding='22'>
				<tr>
				<td><%= image_tag('developers/edcel.jpg', :alt => 'dev', :class => 'img') %></td>
				<td><%= image_tag('developers/cylwyn.jpg', :alt => 'dev', :class => 'img') %></td>
				<td><%= image_tag('developers/nikka.jpg', :alt => 'dev', :class => 'img') %></td>
				<td><%= image_tag('developers/trisha-chan.jpg', :alt => 'dev', :class => 'img') %></td>
				</tr>
				<tr>
					<td>
						<h3 class='saira-extra-condensed-extra-bold-font text-center'><font color='white'>Marie Edcel Balite<br></font></h3>
						<h4 class='saira-extra-condensed-extra-bold-font text-center'><span class='dark-green'>Project Manager</span></h4>
					</td>
					<td>
						<h3 class='saira-extra-condensed-extra-bold-font text-center'><font color='white'>Cylwyn Ronald Creer<br></font></h3>
						<h4 class='saira-extra-condensed-extra-bold-font text-center'><span class='dark-green'>Member</span></h4>
					</td>
					<td>
						<h3 class='saira-extra-condensed-extra-bold-font text-center'><font color='white'>Nikka Marie de Jesus<br></font></h3>
						<h4 class='saira-extra-condensed-extra-bold-font text-center'><span class='dark-green'>Member</span></h4>
					</td>
					<td>
						<h3 class='saira-extra-condensed-extra-bold-font text-center'><font color='white'>Patricia Nicole Opetina<br></font></h3>
						<h4 class='saira-extra-condensed-extra-bold-font text-center'><span class='dark-green'>Member</span></h4>
					</td>
				</tr>
			</table>
		</div>
		<footer class='footer fixed-bottom'>
			<div class='container-fluid text-center'>
				<span class='text-muted open-sans-font'>Copyright © Study Path Tracking System 2018</span>
			</div>
		</footer>
	</div>
</body>

app/views/spts/index.html.erb
<body>
  <div class='container-fluid bg-index full-div'>
    <div class='row full-div'>
      <div class='col-sm-1'>
      </div>
      <div class='col-sm-3 align-self-center'>
        <div class='card'>
          <div class="card-header text-center">
            <%= image_tag('logo/logo-up.png', :alt => 'UP', :class => 'logo-up') %>
          </div>
          <div class='card-body'>
            <% if flash[:login_error] %>
              <p class='text-center open-sans-font'><small><%= flash[:login_error] %></small></p>
            <% end %>
            <ul class='nav nav-tabs nav-fill'>
              <li class='nav-item'>
                <a class='nav-link active' data-toggle='tab' href='#student_login'>
                  <i class='fa fa-user'></i>
                </a>
              </li>
              <li class='nav-item'>
                <a class='nav-link' data-toggle='tab' href='#faculty_login'>
                  <i class='fa fa-user-secret'></i>
                </a>
              </li>
            </ul>
            <br/>
            <div class='tab-content'>
              <div class='tab-pane active container-fluid' id='student_login'>
                <%= form_for :spts, url: spts_student_login_path, local: true do |f| %>
                  <%= f.text_field :user, class: 'form-control open-sans-font', autocomplete: 'off', placeholder: 'Student Number', maxlength: '9'%>
                  <%= f.password_field :password, class: 'form-control open-sans-font', autocomplete: 'off', placeholder: 'Password' %>
                  <br/>
                  <%= f.submit 'Login', class: 'btn btn-outline-primary btn-block open-sans-font' %>
                <% end %>
              </div>
              <div class='tab-pane container-fluid' id='faculty_login'>
                <%= form_for :spts, url: spts_faculty_login_path, local: true do |f| %>
                  <%= f.text_field :user, class: 'form-control open-sans-font', autocomplete: 'off', placeholder: 'Username' %>
                  <%= f.password_field :password, class: 'form-control open-sans-font', autocomplete: 'off', placeholder: 'Password' %>
                  <br/>
                  <%= f.submit 'Login', class: 'btn btn-outline-primary btn-block open-sans-font' %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class='col-sm-8 align-self-center'>
        <h2 class='sub-banner saira-extra-condensed-extra-bold-font'><span class='dark-green'>University of the Philippines</span></h2>
        <h1 class='banner saira-extra-condensed-extra-bold-font'>STUDY PATH TRACKING SYSTEM</h1>
        <%= link_to "About", spts_about_path, class: 'btn btn-outline-primary btn-lg open-sans-font', role: 'button' %>
        <%= link_to "Developers Portal", spts_developers_portal_path, class: 'btn btn-outline-light btn-lg open-sans-font', role: 'button' %>
      </div>
    </div>
    <footer class='footer fixed-bottom'>
      <div class='container-fluid text-center'>
        <span class='text-muted open-sans-font'>Copyright © Study Path Tracking System 2018</span>
      </div>
    </footer>
    
    <!-- Bootstrap core JavaScript-->
    <script src="/assets/vendor/jquery/jquery.min.js"></script>
    <script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  </div>
</body>