config/routes.rb
Rails.application.routes.draw do
  get 'spts/index'
  get 'spts/about', :to => 'spts#about'
  get 'spts/developers_portal', :to => 'spts#developers_portal'
  post 'spts/student_login', :to => 'spts#student_login'
  post 'spts/faculty_login', :to => 'spts#faculty_login'
  delete 'spts/logout', :to => 'spts#logout'
  root 'spts#index'

  get 'student/dashboard', :to => 'students#dashboard'
  get 'student/charts', :to => 'students#charts'
  get 'student/grades', :to => 'students#grades'
  get 'student/unitsEarned', :to => 'students#unitsEarned'
  get 'student/unitsToGo', :to => 'students#unitsToGo'
  
  resources :admins
  get 'admin/dashboard', :to => 'admins#dashboard'
  post 'admin/dashboard', :to => 'admins#dashboard'
  get 'admin/add_new_subject', :to => 'admins#add_new_subject'
  post 'admin/add_new_subject', :to => 'admins#new_subject'
  get 'admin/new_subject', :to => 'admins#new_subject'
  post 'admin/new_subject', :to => 'admins#new_subject'
  get 'admin/new_subject', :to => 'admins#new_subject'
  get 'admin/add_study_path', :to => 'admins#add_study_path'
  get 'admin/view_study_path', :to => 'admins#view_study_path'
  get 'admin/remove_study_path', :to => 'admins#remove_study_path'
  get 'admin/:id/delete_certain_study_path', :to => 'admins#delete_certain_study_path'
  
  resources :study_paths
  get 'study_path/:id/remove_subject', :to => 'study_paths#remove_subject', as: 'remove_subject'
  get 'study_path/:id/add_subject', :to => 'study_paths#add_subject', as: 'add_subject'
  get 'study_path/:id/update_subjects', :to => 'study_paths#update_subjects', as: 'update_subjects'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<!-- Footer -->
<footer class="sticky-footer">
  <div class="container">
    <div class="text-center">
      <small>Copyright © Study Path Tracking System 2018</small>
    </div>
  </div>
</footer>
<!-- Scroll to Top Button-->
<a class="scroll-to-top rounded" href="#page-top">
  <i class="fa fa-angle-up"></i>
</a>
<!-- Bootstrap core JavaScript-->
<script src="/assets/vendor/jquery/jquery.min.js"></script>
<script src="/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
<!-- Core plugin JavaScript-->
<script src="/assets/vendor/jquery-easing/jquery.easing.min.js"></script>
<!-- Page level plugin JavaScript-->
<script src="/assets/vendor/chart.js/Chart.min.js"></script>
<script src="/assets/vendor/datatables/jquery.dataTables.js"></script>
<script src="/assets/vendor/datatables/dataTables.bootstrap4.js"></script>
<!-- Custom scripts for all pages-->
<script src="/assets/js/sb-admin.min.js"></script>
<!-- Custom scripts for this page-->
<script src="/assets/js/sb-admin-datatables.min.js"></script>
<script src="/assets/js/sb-admin-charts.min.js"></script>

app/views/shared/_logout_modal.html.erb
<!-- Logout Modal-->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
        <%= link_to "Logout", spts_logout_path, class: 'btn btn-primary', role: 'button', method: "delete" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navigation.html.erb
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
  <a class="navbar-brand" href="/dashboard">Study Path Tracking System</a>
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarResponsive">
    <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
        <a class="nav-link" href="/student/dashboard">
          <i class="fa fa-fw fa-dashboard"></i>
          <span class="nav-link-text">Dashboard</span>
        </a>
      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Charts">
        <a class="nav-link" href="/student/charts">
          <i class="fa fa-fw fa-area-chart"></i>
          <span class="nav-link-text">Charts</span>
        </a>
      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Grades">
        <a class="nav-link" href="/student/grades">
          <i class="fa fa-fw fa-list"></i>
          <span class="nav-link-text">Grades</span>
        </a>
      </li>
      <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Study Plan">
        <%= link_to study_path_path(@study_path), class: 'nav-link' do %>
          <i class="fa fa-fw fa-graduation-cap"></i>
          <span class="nav-link-text">Study Path</span>
        <% end %>
      </li>
    </ul>
    <ul class="navbar-nav sidenav-toggler">
      <li class="nav-item">
        <a class="nav-link text-center" id="sidenavToggler">
          <i class="fa fa-fw fa-chevron-circle-left"></i>
        </a>
      </li>
    </ul>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
          <i class="fa fa-fw fa-sign-out"></i>Logout
        </a>
      </li>
    </ul>
  </div>
</nav>