config/routes.rb
Rails.application.routes.draw do
  get 'spts/index'
  get 'spts/about', :to => 'spts#about'
  get 'spts/developers_portal', :to => 'spts#developers_portal'
  post 'spts/student_login', :to => 'spts#student_login'
  post 'spts/faculty_login', :to => 'spts#faculty_login'
  delete 'spts/logout', :to => 'spts#logout'
  root 'spts#index'

  get 'student/dashboard', :to => 'students#dashboard'
  get 'student/charts', :to => 'students#charts'
  get 'student/grades', :to => 'students#grades'
  get 'student/unitsEarned', :to => 'students#unitsEarned'
  get 'student/unitsToGo', :to => 'students#unitsToGo'
  
  resources :admins
  get 'admin/dashboard', :to => 'admins#dashboard'
  post 'admin/dashboard', :to => 'admins#dashboard'
  get 'admin/add_new_subject', :to => 'admins#add_new_subject'
  post 'admin/add_new_subject', :to => 'admins#new_subject'
  get 'admin/new_subject', :to => 'admins#new_subject'
  post 'admin/new_subject', :to => 'admins#new_subject'
  get 'admin/new_subject', :to => 'admins#new_subject'
  get 'admin/add_study_path', :to => 'admins#add_study_path'
  get 'admin/view_study_path', :to => 'admins#view_study_path'
  get 'admin/remove_study_path', :to => 'admins#remove_study_path'
  get 'admin/:id/delete_certain_study_path', :to => 'admins#delete_certain_study_path'
  
  resources :study_paths
  get 'study_path/:id/remove_subject', :to => 'study_paths#remove_subject', as: 'remove_subject'
  get 'study_path/:id/add_subject', :to => 'study_paths#add_subject', as: 'add_subject'
  get 'study_path/:id/update_subjects', :to => 'study_paths#update_subjects', as: 'update_subjects'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/study_path.rb
class StudyPath < ApplicationRecord
	has_many :study_path_subjects
	has_many :subjects, :through => :study_path_subjects
end

app/controllers/study_paths_controller.rb
class StudyPathsController < ApplicationController
	before_action :access_crs

	def show
		@course = @student.basic_info
		@my_study_path = StudyPath.find_by degree_id: (Degree.find_by id: params["id"].gsub(".","")).id

		degree_id = Degree.where(name: @course['degree_program'].gsub(".","")).pluck(:id).first
		study_path_record = StudyPath.where(degree_id: degree_id).first

		@my_study_path = {id: study_path_record.id, program_revision_code: study_path_record.program_revision_code, title: study_path_record.title}				
		@my_subjects = StudyPathSubject.where(study_path_id: @my_study_path[:id])
		# puts "@my_subjects = #{@my_subjects}"
		# @my_subjects.each do |subject|

		@myGrades = @student.grades
		
		temp_year = ""
		temp_sem = ""

		@entries = Array.new	
		@entry_persem = Hash.new
		@subject_persem = []

		@my_subjects.each_with_index do |subject, index|			
			if temp_year == "" then temp_year = subject[:year] end
			if temp_sem == "" then temp_sem = subject[:semester] end

			if temp_year != subject[:year] || temp_sem != subject[:semester] || index == @my_subjects.length-1
				@entry_persem[:year] = temp_year
				@entry_persem[:sem] = temp_sem
				@entry_persem[:subjects] = @subject_persem				
				temp_year = subject[:year]
				temp_sem = subject[:semester]				
				@entries << @entry_persem
				@entry_persem = Hash.new
				@subject_persem = Array.new
			end

			entry = Hash.new
			if subject[:subject_id] == nil && subject[:rgep] != nil
				entry[:subject] = RgepCluster.where(id: subject[:rgep]).distinct.pluck(:name).first
				entry[:units] = "#{RgepCluster.where(id: subject[:rgep]).distinct.pluck(:units).first}.0"
			else
				entry[:subject] = Subject.where(id: subject[:subject_id]).distinct.pluck(:subject_id).first
				entry[:name] = Subject.where(id: subject[:subject_id]).distinct.pluck(:name).first
				entry[:units] = "#{Subject.where(id: subject[:subject_id]).distinct.pluck(:units).first}.0"				
			end			
			fake_subject_id = Subject.where(id: subject[:subject_id]).distinct.pluck(:fake_subject_id).join(",")
			fake_subject_name = FakeSubject.where(id: fake_subject_id).distinct.pluck(:subject_code).join(",")		
			entry[:prerequisites] = fake_subject_name

			@subject_persem << entry
		end
		
		@totalUnits = 0
		subjects_taken = Array.new
		# ah_taken = Array.new
		# ssp_taken = Array.new
		# mst_taken = Array.new
		# elective_taken = Array.new
		# pe_taken = Array.new
		# nstp_taken

		# puts @myGrades

		@myGrades.each do |sem|
			entry_persem = Array.new
			sem.each do |entries|				
				if entries.length > 1
					subject = Hash.new
					subject[:subject] = entries[:subj]
					subject[:name] = Subject.where(subject_id: "#{entries[:subj]}").distinct.pluck(:name).join(",")
					subject[:units] = entries[:units]
					subject[:prerequisites] = Subject.where(subject_id: "#{entries[:subj]}").distinct.pluck(:pre_req).join(",")
					subject[:grade] = entries[:finalGrade]


					if entries[:finalGrade].include? " INC " or entries[:finalGrade].include? " 4.0 "
						if !entries[:completionGrade].eql? " "
							subject[:grade] = entries[:completionGrade]
						end
					end

					if (!entries[:finalGrade].eql? " 5.0 " or !entries[:finalGrade].eql? " 4.0 " or !entries[:finalGrade].eql? " INC " or !entries[:finalGrade].eql? " NO GRADE ") and !entries[:units].include? "("
						@totalUnits = @totalUnits + entries[:units].to_i
					end

					if entries[:finalGrade].eql? " INC " and !entries[:completionGrade].eql? " NO GRADE "
						if (!entries[:completionGrade].eql? " 5.0 " or !entries[:completionGrade].eql? " 4.0 ") and !entries[:units].include? "("
							@totalUnits = @totalUnits + entries[:units].to_i
						end
					end

					entry_persem << subject
				end
			end
			subjects_taken << entry_persem
		end
    my_units = Array.new
    
    @myGrades.each do |content|
       my_units << content[(content.length - 1)][:subj]
    end
    
    @totalUnits = 0;
    my_units.each do |unit|
      @totalUnits = @totalUnits + unit[32, 4].to_i
    end
   
   @units = 0
    @elective_count = 0
    @entries.each_with_index do |entry, index|
        @entry_subjects = entry[:subjects]
        @first_sem_grade = @myGrades[index]
        
        @entry_subjects.each do |s|
          @units = @units + s[:units].to_i
        end
        if(!@first_sem_grade.nil?)        
          @first_sem_grade = long_cuts(@first_sem_grade)
          entry_subjects(@entry_subjects)
        end
    end
    @units = @units - 12
    @title = "Study Path"
end

  def entry_subjects(entry_subjects)
   
          entry_subjects.each_with_index do |ent, i|
                 if(ent[:subject] == "GE (AH)")
                    @first_sem_grade.each do |fs|
                      
                      subj = Subject.find_by subject_id: fs[:subj]
                      
                      if(!subj.nil?)
                        if(!subj.rgep.nil?)
                            if(subj.rgep.strip == "GE (AH)")
                              ent[:name] = fs[:subj]
                              ent[:grade] = fs[:finalGrade]
                              fs[:subj] = ""
                              break
                            end
                        end
                      end
                    end
                  elsif (ent[:subject] == "GE (SSP)")
                   @first_sem_grade.each do |fs|
                      
                      subj = Subject.find_by subject_id: fs[:subj]
                      
                      if(!subj.nil?)
                        if(!subj.rgep.nil?)
                            if(subj.rgep.strip == "GE (SSP)")
                              ent[:name] = fs[:subj]
                              ent[:grade] = fs[:finalGrade]
                              fs[:subj] = ""
                              break
                            end
                        end
                      end
                    end
                  elsif (ent[:subject] == "GE (MST)")
                    @first_sem_grade.each do |fs|
                      
                      subj = Subject.find_by subject_id: fs[:subj]
                      
                      if(!subj.nil?)
                        if(!subj.rgep.nil?)
                            
                            if(subj.rgep.strip == "GE (MST)")
                              ent[:name] = fs[:subj]
                              ent[:grade] = fs[:finalGrade]
                              fs[:subj] = ""
                              break
                            end
                        end
                      end
                  end
                  elsif (ent[:subject].include? "NSTP")
                    @first_sem_grade.each do |fs|
                        if(fs[:subj].include?"NSTP")
                          ent[:grade] = fs[:finalGrade]
                        end
                     end
                  elsif (ent[:subject].include? "P.E.")
                    @first_sem_grade.each do |fs|
                        if(fs[:subj].include?"PE")
                          ent[:grade] = fs[:finalGrade]
                          ent[:units] = 2.0
                        end
                     end
                  elsif (ent[:subject].include? "PE")
                    @first_sem_grade.each do |fs|
                        if(fs[:subj].include?"PE")
                          ent[:grade] = fs[:finalGrade]
                        end
                     end
                   elsif (ent[:subject] == "Elective")
                   @first_sem_grade.each do |fs|
                      subj = Subject.find_by subject_id: fs[:subj]
                      if(!subj.nil?)
                        if(!subj.rgep.nil?)
                            if(subj.rgep.strip == "Elective")
                                 ent[:name] = fs[:subj]
                                 ent[:grade] = fs[:finalGrade]
                                 fs[:subj] = ""
                                 break
                            end
                        end
                      end
                   end
                  else
                       @first_sem_grade.each do |fs|
                          if(ent[:subject] == fs[:subj])
                              ent[:grade] = fs[:finalGrade]
                          end
                          if(ent[:subject] == fs[:subj])
                              ent[:grade] = fs[:finalGrade]
                          end
                       end
                   end
             end
  end
	def new
		@title = 'SPTS - Add New Study Path'
	end

	def edit
		@title = 'SPTS - Edit Study Path'
	end

	def update
	end

	def destroy
	end

	def create
    @title = 'SPTS - New Study Path'
    
    if((StudyPath.find_by degree_id: (Degree.find_by name: params["study_path"]["degree_id"].gsub(".","")).id).nil?)
      @my_study_path = StudyPath.create(program_revision_code: params["study_path"]["program_revision_code"], title: params["study_path"]["title"],
      degree_id: (Degree.find_by name: params["study_path"]["degree_id"].gsub(".","")).id)
      @@subject_session = nil
    else
      @my_study_path = StudyPath.find_by degree_id: (Degree.find_by name: params["study_path"]["degree_id"].gsub(".","")).id
      @my_study_path.program_revision_code = params["study_path"]["program_revision_code"]
      @my_study_path.title = params["study_path"]["title"]
      @my_study_path.save
    end
    redirect_to "/admins/#{@my_study_path.id}"
	end

  def long_cuts (grades)
    grades.each_with_index do |grade, index|
        if(grade[:subj].include? "Comm")
           grade[:subj] = grade[:subj].insert(4, ".")
        end
        if(grade[:subj].include? "Hum")
           grade[:subj] = grade[:subj].insert(3, ".")
        end
        if(grade[:subj].include? "Lit")
           grade[:subj] = grade[:subj].insert(3, ".")
        end
        if(grade[:subj].include? "Soc")
            grade[:subj] = grade[:subj].insert(grade[:subj].index("Soc")+3, "ial")

app/helpers/study_paths_helper.rb
module StudyPathsHelper
end

app/views/study_paths/new.html.erb
<body class="fixed-nav sticky-footer bg-dark" id="page-top">
  <%= render partial: "shared/navigation", object: @study_path %>
  <div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="/student/dashboard">Student</a>
        </li>
        <li class="breadcrumb-item">
          <%= link_to "Study Path", study_path_path(@study_path) %>
        </li>
        <li class="breadcrumb-item active">Add New Study Path</li>
      </ol>
      <br>
      <br>
      <div class="row container-fluid">
        <div class="col-3"></div>
        <div class="card col-6">
          <div class="card-body">
            <h3 class="text-primary">Creating new study path</h3>
            <h6>Please specify the necessary things below.</h6>
            <br>
            <%= form_for :study_path, url: study_paths_path, local: true do |f| %>
              <%= f.text_field :program_revision_code, class: 'form-control form-study-path', autocomplete: 'off', placeholder: 'Program Revision Code' %> 
              <%= f.select :degree_id, [['B.S. IN COMPUTER SCIENCE', '1']], {include_blank: 'Name'}, {class: 'form-control form-study-path'} %>
              <%= f.text_field :title, class: 'form-control form-study-path', autocomplete: 'off', placeholder: 'Title' %>
              <br>
              <%= f.submit 'Add New Study Path',class: 'form-control btn btn-primary'%>
            <% end %>
          </div>
        </div>
      </div>
      <%= render "shared/logout_modal" %>
    </div>
    <%= render "shared/footer" %>
  </div>
</body>

app/views/study_paths/show.html.erb
<body class="fixed-nav sticky-footer bg-dark" id="page-top">
  <%= render partial: "shared/navigation", object: @study_path %>
  <div class="content-wrapper">
    <div class="container-fluid">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="/student/dashboard">Student</a>
        </li>
        <li class="breadcrumb-item active">Study Path</li>
      </ol>

      <% if @my_study_path.nil? %>
        <div class="text-center center-middle-text">
          <div class="col-12">
            <i class="fa fa-fw fa-frown-o fa-4x"></i>
            <br>
            <h3>No Study Path Found</h3>
            <p>It seems that the division haven't uploaded a study path of the degree program yet.</p>
            <br>
            <%= link_to "Add New Study Path", new_study_path_path, class: 'btn btn-primary btn-md open-sans-font', role: 'button' %>
          </div>
        </div>
      <% else %>
        <div class="row">
          <div class="col-lg-12">
            <div class="card mb-3">
              <div class="card-header">
                <div class="text-left">
                  <strong>Program Code : </strong><span><%= @my_study_path[:degree_id] %></span>
                </div>
                <div class="text-left">
                  <strong>Program Revision Code : </strong><span><%= @my_study_path[:program_revision_code] %></span>
                </div>
                <div class="text-left">
                  <strong>Name : </strong><span><%= @basic_info['degree_program'] %></span>
                </div>
                <div class="text-left">
                  <strong>Title : </strong><span><%= @my_study_path[:title] %></span>
                </div>
              </div>
              <div class="card-body">
                <div class="table-responsive">
                  <table class="table table-bordered" width="100%" cellspacing="0">
                    <thead class="thead-light">
                      <tr>
                        <th>Subject</th>
                        <th>Name</th>
                        <th>Units</th>
                        <th>Prerequisites</th>
                        <th>Grade</th>
                      </tr>
                    </thead>
                    <% if !@entries.nil? %>
                      <% @entries.each_with_index do |content, i| %>
                        <tbody>
                          <tr class="table-primary">
                            <td colspan="5">
                              <h6 class="d-inline"><%= "#{content[:year]} Year (#{content[:sem]} Semester)" %></h6>                      
                            </td>
                          <tr>  
                        </tbody>
                        <tbody>
                          <% if !content[:subjects].nil? %>
                            <% for i in 0..(content[:subjects].length - 1) %>
                              <tr>
                                <td><%= content[:subjects][i][:subject] %></td>
                                <td><%= content[:subjects][i][:name] %></td>
                                <td><%= content[:subjects][i][:units] %></td>
                                <td><%= content[:subjects][i][:prerequisites] %></td>
                                <td><%= content[:subjects][i][:grade] %></td>
                              </tr>
                            <% end %>
                          <% end %>
                        </tbody>
                      <% end %>
                    <% end %>
                  </table>
                </div>
              </div>
              <div class="card-header">
                <h6>Total Units Earned : <%= @totalUnits %></h6>  
              </div>
              <div class="card-header">
                <h6>Total Units Needed : <%= @units %></h6>  
              </div>
            </div>
          </div>
        </div>
      <% end %>
      <%= render "shared/logout_modal" %>
    </div>
    <%= render "shared/footer" %>
  </div>
</body>

app/views/study_paths/update_subjects.html.erb
<body class="fixed-nav sticky-footer bg-dark" id="page-top">
  <div class="container-fluid">
      <div class ="content_wrapper bg-light">
      <!-- Breadcrumbs-->
      <ol class="breadcrumb">
        <li class="breadcrumb-item">
          <a href="/admin/dashboard">Admin</a>
        </li>
        <li class="breadcrumb-item">
          <%= link_to "Study Path", "/admins/#{@study_path.id}" %>
        </li>
        <li class="breadcrumb-item active">Update Subjects</li>
      </ol>
      <div class="card mb-3">
        <div class="card-header">
          <i class="fa fa-fw fa-bookmark"></i> <%= @year %> Year - <%= @semester %> Semester
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" width="100%" cellspacing="0" id="subjectsTable">
              <thead class="thead-light">
                <tr>
                  <th>Subject</th>
                  <th>Name</th>
                  <th>Units</th>
                  <th>Prerequisites</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                <% if !@current_subjects.nil? %>
                  <% @current_subjects.each do |subj| %>
                    <tr>
                      <% if subj.instance_of? RgepCluster %>
                        <td><%= subj.name%></td>
                        <td></td>
                        <td></td>
                        <td></td>
                      <% else %>
                         <td><%= subj.subject_id %></td>
                         <td><%= subj.name %></td>
                         <td><%= subj.units %></td>
                         <td><%= subj.pre_req %></td>
                      <% end %>
                      <td>
                         <%= link_to remove_subject_path("study_path" => @study_path.id, "subject" => subj.id, "year" => @year, "semester" => @semester), class: 'btn btn-danger btn-sm', role: 'button' do %>
                            <i class="fa fa-fw fa-save"></i> Remove
                          <% end %>
                      </td>
                    </tr>
                  <% end %>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
        <div class="card-footer small text-muted">
          <i class="fa fa-fw fa-database"></i> Number of Units :
        </div>
      </div>
      <div class="card mb-3">
        <div class="card-header">
          <i class="fa fa-fw fa-book"></i> Subject Offerings</div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th>Subject</th>
                  <th>Name</th>
                  <th>Units</th>
                  <th>Prerequisites</th>
                  <th>Actions</th>
                </tr>
              </thead>
              <tbody>
                <% @subjects.each do |content| %>
                    <tr>
                      <td><%= content.subject_id %></td>
                      <td><%= content.name %></td>
                      <td><%= content.units %></td>
                      <td><%= content.pre_req%></td>
                      <td>
                          <%= link_to add_subject_path("study_path" => @study_path.id, "subject" => content.id, "year" => @year, "semester" => @semester), class: 'btn btn-warning btn-sm', role: 'button' do %>
                            <i class="fa fa-fw fa-save"></i> Add
                          <% end %>
                      </td>
                    </tr>
                  <% end %>
              </tbody>
            </table>
          </div>
        </div>
        <div class="card-footer small text-muted">All subjects are based from crs.upv.edu.ph.</div>
       </div>
      </div>
     </div>
</body>